package com.aziz.lonelyapp.model;

import jakarta.persistence.*;


import java.util.Date;


/**
 * This class represents a direct message entity in the application.
 * It is mapped to the "direct_messages" table in the database using JPA annotations.
 */
@Entity
@Table(name = "direct_messages")
public class MessageEntity {

    /**
     * The unique identifier of the message.
     * It is auto-generated by the database and mapped to the "id" column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    /**
     * The sender of the message.
     * It is mapped to the "sender" column in the database.
     */
    @Column(name = "sender")
    private String from;

    /**
     * The receiver of the message.
     * It is mapped to the "receiver" column in the database.
     */
    @Column(name = "receiver")
    private String to;

    /**
     * The content of the message.
     * It is mapped to the "message" column in the database.
     */
    @Column(name = "message")
    private String message;

    /**
     * The timestamp of when the message was sent.
     * It is stored as a Unix timestamp (milliseconds since epoch) and mapped to the "sentdate" column in the database.
     */
    @Column(name = "sentdate")
    private Long sentdate;

    // Getters and setters for each field
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Long getSentdate() {
        return sentdate;
    }

    public void setSentdate(Long sentdate) {
        this.sentdate = sentdate;
    }
}